apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: shricicd
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: shrilabelcicd
    spec:
      containers:
      - name: my-app
        image: shrikntsharma/javahometech:latest
        ports:
        - containerPort: 8090
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m

---
apiVersion: v1
kind: Service
metadata:
  name: shricicd
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: shricicd
